### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by farnaf** [oplikos/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] Last example counts keystrokes and shows how to run remotely saving time
- [x] Text is formatted in a way that was easy for grader to read
- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [x] All titles of sections are formatted as headers or similar
- [x] All screenshots correspond to the described steps
- [x] Lab report is on its own page, not the index page

Additional comments from your grader:

Hi there! I, unfortunately, cannot give you credit due the unchecked boxes (requirements we're looking for). For full credit, please update your lab report and make sure the described steps you've captured in images are actual Markdown text with the required formatting listed above. 
Feel free to comment below any questions related to the rubric/feedback!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by oplikos** [comment]
hello, I'm requesting a regrade, please.

**Comment by farnaf** [comment]
Hi, could you submit a regrade request on Gradescope so I can review?

Edit: I see it now!

**Comment by oplikos** [comment]
thank you I just submit a request for regrading on gradscope.
thank you

**Comment by farnaf** [comment]
Everything looks good!
