### ISSUE TITLE
Lab Report 4 Feedback 

### ISSUE THREAD

**Issue by mrkylesmith** [oplikos/cse15l-lab-reports#4]
Here is your feedback for Lab Report 4:

- [x] Provides link to their markdown-parse repository 
- [] Provides link to the markdown-parse repository they reviewed
- Please provide a direct link to the `markdown-parse` repo that you reviewed 

Snippet 1

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 2

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 3

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Additional comments from your grader:
Good job overall, you including all the necessary screenshots and explanations.  Please add a link to the repo that you reviewed at the top of the report, next to where you put the link to your own repo, for full credit.  Also I might suggest that you give each section headers, and make sure you are writing complete sentences and try to use proper punctuation with your descriptions and writing in the lab report.

Feel free to comment below any questions about the rubric/feedback

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by oplikos** [comment]
issue fixed I submit regrading

**Comment by mrkylesmith** [comment]
I see your updated changes with the links and section headers, well done.  I have updated your score.
